### ISSUE TITLE
Publish old version as a separate extension? 

### ISSUE THREAD

**Issue by jonaswalekvist** [bfanger/pixi-inspector#104]
Hi, i have been using pixi-inspector for a long time now, but since v 2 I'm sad to say that this is close to useless now. It might not be in the future, but right now I'm sad because this has been a super useful tool. 

Would it be possible for you to publish the old version again for example pixi-inspector-legacy or something so we can still enjoy all the great things it can do while you work on this new version? 

Here are just a few things that are a game-breaker for me atm. 

1. It does not play well with iframes. I run pixi applications in a environment where the app is in an iframe. I eventually manage to get the inspector running, though it's drawing the outlines of display object as though it would be in the root document, making everything hopelessly out of sync with the application. 

2. The parameters open for manipulation is way to limited now. Sure, before there where a lot that i didn't use. But to be limited to only the basic transforms is not good enough. I'm missing skew, alpha, visible, tint, blend mode etc. 

3. And just convenience wise, I'm missing being able to use arrow keys to "step" values in increments (altering step value with shift and alt keys.) 

Sure i understand that you want to make it look and feel better. But i have never had a problem with the looks.

**Comment by bfanger** [comment]
You can download the old version from the https://github.com/bfanger/pixi-inspector/releases/tag/v1.0.0 page

Go to the `chrome://extensions` settings page and use the "load unpacked extension" to use the older version, which should work until [January 2024](https://developer.chrome.com/blog/more-mv2-transition/).

1. Should be fixed in the next update
2. Some are added in the update, not all, for blendmode I want to implement a dropdown
3. I want to implement the mouse drag behavior from [Blender](https://blender.org/) and  'g' to grab  (mousemove or  arrow keys to move)
