### ISSUE TITLE
chrome don't has the tab "PixiJS"

### ISSUE THREAD

**Issue by lidog** [bfanger/pixi-inspector#116]
I had add the code 
`/* eslint-disable */
    globalThis.__PIXI_APP__ = app;`

but my chrome tools don't show the tab PixiJs;

wish your help！

**Comment by bfanger** [comment]
Did you install the extension from the chrome web store?

**Comment by lidog** [comment]
I had install it by zip；（ https://github.com/bfanger/pixi-inspector/releases/tag/2.6.0）;
I also turn on the enable button;
<img width="676" alt="image" src="https://user-images.githubusercontent.com/22496521/232660160-bf0801bd-c034-4063-b163-ac1e03b6aa33.png">

But  the chrome extension button icon is gray；
<img width="257" alt="image" src="https://user-images.githubusercontent.com/22496521/232660092-c4798ea6-599f-4840-8101-684426241f60.png">

**Comment by bfanger** [comment]
The icon in next to the addresbar is disabled, the extension doesn't have a page action, so that is to be expected.

I see you've loaded the extension via the filesystem but the zip doesn't contain the compiled version of the extension only the source. 

Run `pnpm install && pnpm build` then a `apps/chrome-extension/build` folder will appear, which you can load in Chrome.

**Comment by lidog** [comment]
Thanks a lot for your help！！
