### ISSUE TITLE
From Pixi Inspector 1.x, Restore the selected object indicator in the latest version.

### ISSUE THREAD

**Issue by RaishavHanspal** [bfanger/pixi-inspector#128]
I have used the Pixi dev-tools 1.x extensively and I really liked the extended number of options it had (properties on various Pixi objects).
One of them was a very nice feature:
There used to be a light blue transparent rectangle indicator of bounds of the hovered display object in the scene explorer. This was similar to what we have in HTML, It was a very intuitive way of selecting the right object.

Kindly restore this - also, please state why did we not have this feature in the latest release. :)

**Comment by bfanger** [comment]
Due to the changes in what Chrome allows extensions to do, the extension is rewriten which also went from Vue to Svelte.

The new version mimics the UI from [Blender](https://blender.org/) which doesn't have behavior when hovering.
But it's useful, so i've restored the feature in 2.9.0.

Thanks for reminding me.
